### PR TITLE
Regen lockfile based on Node >= 16 and npm >= 7

### PR DESCRIPTION
**Pull request by mcmire**
[npm v7 introduced a different lockfile format][1]. This change ensures
that everyone working on this project is using npm >= 7 — and Node 16,
which is the first LTS release to use npm 7 — so that they are using
this format.

[1]: https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#handling-old-lockfiles

### CODE REVIEW

**Comment by Gudahtt** [comment]
Probably best to include a minimum node/npm version in `package.json` to prevent the lockfile from regressing again from someone installing with an older version.

**Comment by mcmire** [comment]
Good call. Is there something specific we should use, you think? v14 to match our other libraries, or v16 (since it's the latest LTS)?

**Comment by mcmire** [comment]
Updated appropriately.

**Comment by Imimi111** [comment]
Leave a comment

**Review by Imimi111 — COMMENTED** [review]
Leave review

**Pull request merged**
